lab04/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recetas.urls'))
]

recetas/urls.py
from django.urls import path
from . import views

app_name = 'receta'

urlpatterns = [
    path('',views.Index, name='index'),
    path('receta/', views.Recetas, name='receta'),
    path('preparacion/<int:autor_id>/<int:receta_id>/', views.Preparacion, name='preparacion'),
    path('register', views.Register, name='register'),
]

recetas/models.py
from django.db import models

class Autor(models.Model):
    nombre = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.nombre
    
class Receta(models.Model):
    titulo = models.CharField(max_length=100, unique=True)
    ingredientes = models.TextField(help_text='Redacta los ingredientes')
    preparacion = models.TextField()
    tiempo_registro = models.DateTimeField(auto_now=True)
    imagen = models.CharField(max_length=300)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo
    
class Comentario(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE)
    texto = models.TextField(help_text='tu comentario', verbose_name='Comentario')

    def __str__(self):
        return self.texto
    

recetas/views.py
from django.shortcuts import render 
from .models import Autor, Receta, Comentario


def Index(request):
    return render(request, 'receta/index.html')

def Recetas(request):
    autor_nombre = Autor.objects.all()
    if "registrado" in request.POST:
        contador = 0
        title = request.POST['titulo']
        for i in Receta.objects.all():
            if title == i.titulo:
                contador = contador + 1
        if contador == 0:
            nombre = request.POST['autor']
            email = nombre.lower().replace(" ","")+'@gmail.com'
            autor = Autor(nombre = nombre, email = email)
            autor.save()
            titulo = request.POST['titulo']
            ingredientes = request.POST['ingredientes']
            preparacion = request.POST['preparacion']
            imagen = request.POST['imagen']
            autor = autor
            receta = Receta(titulo = titulo, ingredientes = ingredientes,  preparacion = preparacion, imagen = imagen, autor = autor)
            receta.save()
    context = {
        'autor' : autor_nombre
    }
    return render(request, 'receta/receta.html', context)

def Preparacion(request, autor_id, receta_id):
    autor = Autor.objects.get(pk=autor_id)
    receta = autor.receta_set.get(pk=receta_id)
    if "comentado" in request.POST:
        comentario = Comentario(texto = request.POST['comentario'], receta = receta)
        comentario.save()
    context = {
        'receta' : receta,
    }
    return render(request, 'receta/preparacion.html', context)

def Register(request):
    return render(request, 'receta/register.html')

recetas/templates/receta/index.html
{% extends "main.html" %}
{% load static %}
{% block btnver %}
<a class="btn btn-lg btn-primary" href="{% url 'receta:receta' %}">Ver Recetas</a>
{% endblock %}

recetas/templates/receta/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with FoodHut landing page.">
    <meta name="author" content="Devcrud">
    <title>Index</title>

    <!-- font icons -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'vendors/themify-icons/css/themify-icons.css' %}">

    <link rel="stylesheet" href="{% static 'vendors/animate/animate.css' %}">

    <!-- Bootstrap + FoodHut main styles -->
    <link rel="stylesheet" href="{% static 'css/foodhut.css' %}">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">

    <!-- Navbar -->
    <nav class="custom-navbar navbar navbar-expand-lg navbar-dark fixed-top" data-spy="affix" data-offset-top="10">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" style="margin: 20px;"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'receta:index' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'receta:receta' %}">Recetas</a>
                </li>
            </ul>
            <a class="navbar-brand m-auto" href="#">
                <img src="https://raw.githubusercontent.com/rqueaArequipa/LAB-04-DAE/main/recetas/static/imgs/Logo_Recetas.png" class="brand-img" alt="" style="width: 35%;">
                <span class="brand-txt">Recetas QJ</span>
            </a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'receta:register' %}" class="btn btn-primary ml-xl-4">Registrar Recetas</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block preparacion %}
    {% block receta %}
    <!-- header -->
    <header id="home" class="header">
        <div class="overlay text-white text-center">
            <h1 class="display-2 font-weight-bold my-3">RECETAS</h1>
            <h2 class="display-4 mb-5">Deliciosos &amp; Faciles de Preparar</h2>
            {% block btnver %}
            {% endblock %}
        </div>
    </header>
    {% endblock %}
    {% endblock %}
    <!-- page footer  -->
    <div class="container-fluid bg-dark text-light has-height-md middle-items border-top text-center wow fadeIn">
        <div class="row">
            <div class="col-sm-4">
                <img src="https://raw.githubusercontent.com/rqueaArequipa/LAB-04-DAE/main/recetas/static/imgs/Logo_Recetas.png" class="brand-img" alt="" style="width: 35%;">
            </div>
            <br>
            <div class="col-sm-4">
                <h3>CONTACTO</h3>
                <P class="text-muted">ruben.quea@tecsup.edu.pe</P>
            </div>
            <div class="col-sm-4">
                <h3>PAGINA WEB</h3>
                <a href="https://rqueaarequipa.github.io/">QJ Dveloper</a>
            </div>
        </div>
    </div>
    <div class="bg-dark text-light text-center border-top wow fadeIn">
        <p class="mb-0 py-3 text-muted small">&copy; Copyright
            <script>document.write(new Date().getFullYear())</script>  <i class="ti-heart text-danger"></i>
            <a href="https://rqueaarequipa.github.io/">QJ Dveloper</a>
        </p>
    </div>
    <!-- end of page footer -->

    <!-- core  -->
    <script src="{% static 'vendors/jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/bootstrap.bundle.js' %}"></script>

    <!-- bootstrap affix -->
    <script src="{% static 'vendors/bootstrap/bootstrap.affix.js' %}"></script>

    <!-- wow.js -->
    <script src="{% static 'vendors/wow/wow.js' %}"></script>

    <!-- google maps -->
    <script async defer
        src="{% static 'https://maps.googleapis.com/maps/api/js?key=AIzaSyCtme10pzgKSPeJVJrG1O3tjR6lk98o4w8&callback=initMap' %}"></script>

    <!-- FoodHut js -->
    <script src="{% static 'js/foodhut.js' %}"></script>

</body>

</html>

recetas/templates/receta/preparacion.html
{% extends "main.html" %}
{% load static %}
{% block preparacion %}
<!-- REVIEWS Section  -->
<div id="testmonial" class="container-fluid wow fadeIn bg-dark text-light has-height-lg middle-items">
    <h2 class="section-title my-5 text-center"></h2>
    <h4 class="pt20 pb20"></h4><br>
    <div class="row mt-3 mb-5">
        <div class="col-md-12 my-3 my-md-0">
            <div class="testmonial-card">
                <h3 class="testmonial-title">{{ receta }}</h3>
                <h6 class="testmonial-subtitle">Autor: {{ receta.autor }}</h6>
                <div class="testmonial-body">
                    <h4 class="pt20 pb20">Ingredientes</h4>
                    <p>{{receta.ingredientes}}</p>
                    <h4 class="pt20 pb20">Preparacion</h4>
                    <p>{{ receta.preparacion }}</p>
                    <img src="{{ receta.imagen }}" alt="" class="rounded-0 card-img-top mg-responsive">
                </div>
                <h4 class="pt20 pb20">Comentarios</h4>
                {% for comentario in receta.comentario_set.all %}
                <p>{{comentario.texto}}</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<!-- book a table Section  -->
<div class="container-fluid has-bg-overlay text-center text-light has-height-lg middle-items" id="book-table">
    <form action="{% url 'receta:preparacion' receta.autor.id receta.id %}" method="POST">
        {% csrf_token %}
        <div class="">
            <h2 class="section-title mb-5">Comentario</h2>
            <div class="row mb-5">
                <div class="col-sm-6 col-md-12 col-xs-12 my-2">
                    <input type="text" id="booktable" class="form-control form-control-lg custom-form-control" name="comentario"
                        placeholder="comentario">
                </div>
            </div>
            <input class="btn btn-lg btn-primary" id="rounded-btn" type="submit" value="Comentar" name="comentado">
        </div>
    </form>
</div>
{% endblock %}

recetas/templates/receta/receta.html
{% extends "main.html" %}
{% load static %}
{% block receta %}
<!-- BLOG Section  -->
<div id="blog" class="container-fluid bg-dark text-light py-5 text-center wow fadeIn">
    <h2 class="section-title my-5 text-center"></h2>
    <h2 class="section-title py-5">Recetas</h2>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="foods" role="tabpanel" aria-labelledby="pills-home-tab">
            <div class="row">
                {% for autor in autor %}
                <div class="col-md-4">
                    <div class="card bg-transparent border my-3 my-md-0">
                        {% for receta in autor.receta_set.all %}
                        <img src="{{ receta.imagen }}" alt="#" class="rounded-0 card-img-top mg-responsive" style="height: 250px;">
                        <div class="card-body">
                            <h1 class="text-center mb-4"><a href="/preparacion/{{autor.id}}/{{receta.id}}/" class="badge badge-primary">Como se prepara</a></h1>
                            {% endfor %}
                            <h4 class="pt20 pb20">Autor</h4>
                            <p class="text-white">{{ autor.nombre }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

recetas/templates/receta/register.html
{% extends "main.html" %}
{% load static %}
{% block preparacion %}
<div id="testmonial" class="container-fluid wow fadeIn bg-dark text-light has-height-lg middle-items">
    <h2 class="section-title my-5 text-center"></h2>
    <h4 class="pt20 pb20"></h4><br>
    <div class="row mt-3 mb-5">
        <div class="col-md-12 my-3 my-md-0">
            <div class="testmonial-card">
                <h3 class="testmonial-title">Registrar una nueva receta</h3>
                <div class="testmonial-body">
                    <form action="{% url 'receta:receta' %}" method="post">
                        {% csrf_token %}
                        <!-- book a table Section  -->
                        <div class="container-fluid has-bg-overlay text-center text-light middle-items"
                            id="book-table">
                            <div class="">
                                <div class="row mb-5">
                                    <div class="col-sm-6 col-md-6 col-xs-12 my-2">
                                        <input type="text" name="autor"
                                            class="form-control form-control-lg custom-form-control"
                                            placeholder="Autor" required>
                                    </div>
                                    <div class="col-sm-6 col-md-6 col-xs-12 my-2">
                                        <input type="text" name="titulo"
                                            class="form-control form-control-lg custom-form-control"
                                            placeholder="Titulo" required>
                                    </div>

                                    <div class="col-sm-6 col-md-6 col-xs-12 my-2">
                                        <textarea type="text"  name="ingredientes"
                                            class="form-control form-control-lg custom-form-control"
                                            placeholder="Ingredientes" required></textarea>
                                    </div>
                                    <div class="col-sm-6 col-md-6 col-xs-12 my-2">
                                        <textarea type="text" name="preparacion"
                                            class="form-control form-control-lg custom-form-control"
                                            placeholder="Como se Prepara" required></textarea>
                                    </div>

                                    <div class="col-sm-6 col-md-12 col-xs-12 my-2">
                                        <input type="text"  name="imagen"
                                            class="form-control form-control-lg custom-form-control"
                                            placeholder="Link de la imagen" required>
                                    </div>
                                </div>
                                <input name="registrado" type="submit" class="btn btn-lg btn-primary" id="rounded-btn" value="Registrar">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}